# Generated by Django 2.1.15 on 2020-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_article_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='world_cup',
            field=models.IntegerField(default=0),
        ),
    ]
